services:
  db:
    container_name: postgresdb
    image: postgres:18.6
    restart: unless-stopped # `always` Is always restarted, `unless-stopped` only restarted if not deliberately stopped
    environment:
      - POSTGRES_PASSWORD=pw # [required]
      - POSTGRES_USER=user # [optional] default is postgres
      - POSTGRES_DB=pdb # [optional] default is POSTGRES_USER
    ports:
      - 5432:5432
    volumes:
      #- ./db-data:/var/lib/postgresql/ # Bind mount
      - pg_data:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d pdb"]
      interval: 10s # Every 10 s the test is triggered
      timeout: 5s # The maximal time one test is allowed to run
      retries: 5 # Number of times a health test is allowed to fail, afterwards container is stated as unhealthy
      start_period: 30s # Within 30 s failures are not considered for retries
  # [Docker]: docker run --name postgresdb_drun -e POSTGRES_PASSWORD=pw -d -p 5433:5432 -v ./db-data:/var/lib/postgresql --rm  postgres:18.6

  db-migration:
    container_name: migration
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile.migration
    environment:
      - DATABASE_URL=postgresql+psycopg://user:pw@postgresdb:5432/pdb
    depends_on:
      db:
        condition: service_healthy
  adminer:
    container_name: dbclient
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      # - postgresdb # first start postgresdb, then start dbclient
      db:
        condition: "service_healthy" # only start dbclient when postgresdb is healthy / ready to accept traffic
  # [Docker]: docker run --name adminer_client -d -p 8081:8080 --rm adminer
  # [localhost:8081] Server: host.docker.internal

volumes:
  pg_data: # if you dont specific this you get `service "db" refers to undefined volume pg_data ...`
